ticketApi:
  - URL: https://docs.aws.amazon.com/
    IsActive: true
  - URL: https://github.com/
    IsActive: true
  - URL: https://facebook.com
    IsActive: true
  - URL: https://github.com/
    IsActive: true
  - URL: https://aws.com/
    IsActive: true
